#! /bin/bash
# delete host route from host-IP through interface to specified destination IP address
if [ -z "$1" ]  && [ -z "$2" ] && [-z "$3" ] && [-z "$4" ]	# if incomplete command line options
then
    echo "Error:"
    echo "Usage: delete-host-route-remote host-IP gw host-interface destination-IP"
    echo "       e.g.   delete-host-route-remote 172.17.0.45 10.43.200.10 eth1 34.5.46.122"
    exit
else
    EXIST=`ssh jtb@$1 ip route show $4 | wc -l`
    if [ $EXIST -eq 1 ]
    then
        echo "On host $1 deleting ip route del $4/32 via $2 dev $3 ..."
        ssh jtb@$1 sudo ip route del $4/32 via $2 dev $3
    else
        #echo "EXIST = $EXIST"
        echo "Route to delete doesn't exist on host $1 for destination-IP $4"
    fi
fi
