#! /bin/bash
# del host route to specified IP address on local machine if it exists
if [ -z "$1" ]  && [ -z "$2" ]	# if $1 is unset
then
    echo "Error:"
    echo "Usage: del-host-route-if-missing host interface"
    echo "       e.g.   del-host-route-if-missing 34.5.46.122 eth1"
    exit
else
    EXIST=`ip route show $1 | wc -l`
    if [ $EXIST -eq 0 ]
    then
        sudo ip route del $1/32 dev $2
    fi
fi
