#!/bin/bash
# Display NAT tracked connection updates (tail -f)
# Note 1: Lists only connections from offered flow networks 10.43.x.x
# Note 2: Enumerated entries not listed are sources outside of 10.43 network
SRC=10.43.x.x		# see only NAT active connections from source switches
echo "For debugging only -- script doesn't terminate..."
echo "Listing only live updates of tracked connections from "$SRC" networks"
sudo /usr/sbin/conntrack -E  | grep "10.43."
